import React, { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Shield, CheckCircle2, AlertTriangle } from "lucide-react";
import { MedicalDisclaimer } from "@/components/disclaimer";

export default function AdrReportForm() {
  const [submitted, setSubmitted] = useState(false);
  const [formData, setFormData] = useState({ drugName: "", reaction: "", severity: "moderate", patientAge: "", description: "", outcome: "" });

  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); if (!formData.drugName || !formData.reaction || !formData.description) return; setSubmitted(true); };

  if (submitted) {
    return (<div className="max-w-2xl mx-auto mt-12 p-6"><Card className="text-center shadow-sm border-green-100"><CardContent className="pt-12 pb-12 space-y-6"><div className="mx-auto w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center"><CheckCircle2 className="h-8 w-8" /></div><h2 className="text-2xl font-bold text-gray-900">Report Successfully Submitted</h2><p className="text-gray-500 max-w-md mx-auto">Thank you for contributing to pharmacovigilance. Your report has been securely recorded.</p><Button onClick={() => { setSubmitted(false); setFormData({ drugName: "", reaction: "", severity: "moderate", patientAge: "", description: "", outcome: "" }); }}>Submit Another Report</Button></CardContent></Card></div>);
  }

  return (<div className="max-w-3xl mx-auto space-y-6 p-6 bg-gray-50 min-h-screen"><div><h1 className="text-3xl font-bold tracking-tight text-gray-900">Report Adverse Reaction</h1><p className="text-gray-500 mt-1">Submit an official report for an unexpected or dangerous reaction to a medication.</p></div><MedicalDisclaimer /><div className="bg-amber-50 border border-amber-200 text-amber-800 p-4 rounded-lg flex gap-3"><AlertTriangle className="h-5 w-5 text-amber-600 shrink-0" /><div><p className="font-medium">Important</p><p className="text-sm">If this is a medical emergency, please call your local emergency services immediately.</p></div></div><form onSubmit={handleSubmit}><Card className="shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Shield className="h-5 w-5 text-blue-600" />Reporting Form</CardTitle><CardDescription>All information is kept strictly confidential.</CardDescription></CardHeader><CardContent className="space-y-6"><div className="grid gap-6 md:grid-cols-2"><div className="space-y-2"><Label>Suspected Drug <span className="text-red-500">*</span></Label><Input placeholder="Name of the medication" value={formData.drugName} onChange={e => setFormData({...formData, drugName: e.target.value})} required /></div><div className="space-y-2"><Label>Primary Reaction <span className="text-red-500">*</span></Label><Input placeholder="e.g. Severe Rash, Anaphylaxis" value={formData.reaction} onChange={e => setFormData({...formData, reaction: e.target.value})} required /></div></div><div className="grid gap-6 md:grid-cols-2"><div className="space-y-2"><Label>Severity</Label><Select value={formData.severity} onValueChange={(v) => setFormData({...formData, severity: v})}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mild">Mild</SelectItem><SelectItem value="moderate">Moderate</SelectItem><SelectItem value="severe">Severe</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Patient Age</Label><Input type="number" placeholder="Age at time of reaction" value={formData.patientAge} onChange={e => setFormData({...formData, patientAge: e.target.value})} /></div></div><div className="space-y-2"><Label>Detailed Description <span className="text-red-500">*</span></Label><Textarea placeholder="Describe the reaction, when it started, and how it progressed..." className="min-h-[120px]" value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} required /></div><div className="space-y-2"><Label>Outcome Status</Label><Input placeholder="e.g. Recovered, Recovering, Admitted to hospital" value={formData.outcome} onChange={e => setFormData({...formData, outcome: e.target.value})} /></div></CardContent><CardFooter className="bg-gray-50 border-t flex justify-between px-6 py-4"><span className="text-xs text-gray-500">* Required fields</span><Button type="submit">Submit Official Report</Button></CardFooter></Card></form></div>);
}